## Raiblocks CI config

image: ubuntu:xenial

stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.linux_template: &linux_cfg
  variables:
    BOOST_ROOT: /usr/local/boost
    CC: clang
    CXX: clang++

  artifacts:
    expire_in: 2d
    paths:
    - build*/*.tar*
    - build*/*_test
    - csa_results
    - build*/SHA1SUMS

  script:
    - ./ci/build-gitlab.sh


Arch Linux:
  <<: *linux_cfg
  stage: build
  image: pritunl/archlinux:latest

  before_script:
    - pacman --noconfirm -Syu base-devel qt5-tools xorg-server-xvfb clang clang-tools-extra cmake boost boost-libs ninja lsb-release

  script:
    - mkdir -p csa_results/
    - scan-build -o csa_results/ ./ci/build-gitlab.sh


# Disabled, dependency on newer Qt than avail
.Ubuntu Linux Trusty:
  <<: *linux_cfg
  stage: build
  image: ubuntu:trusty
  variables:
    CC: gcc
    CXX: g++
    FLAVOR: trusty

  before_script:
    - ./ci/ubuntu_prep.sh
    - ./ci/bootstrap_boost.sh


Ubuntu Linux Artful:
  <<: *linux_cfg
  stage: build
  image: ubuntu:artful
  variables:
    FLAVOR: artful

  before_script:
    - ./ci/ubuntu_prep.sh
    - ./ci/bootstrap_boost.sh

Ubuntu Linux Xenial:
  <<: *linux_cfg
  stage: build
  image: ubuntu:xenial
  variables:
    FLAVOR: xenial

  before_script:
    - ./ci/ubuntu_prep.sh
    - ./ci/bootstrap_boost.sh

Ubuntu Linux Xenial Beta:
  <<: *linux_cfg
  stage: build
  image: ubuntu:xenial
  variables:
    FLAVOR: xenial
    BETA: 1

  before_script:
    - ./ci/ubuntu_prep.sh
    - ./ci/bootstrap_boost.sh

Xenial OPTIMIZED:
  <<: *linux_cfg
  stage: build
  image: ubuntu:xenial
  variables:
    FLAVOR: xenial
    SIMD: 1

  before_script:
    - ./ci/ubuntu_prep.sh
    - ./ci/bootstrap_boost.sh

Artful OPTIMIZED:
  <<: *linux_cfg
  stage: build
  image: ubuntu:artful
  variables:
    FLAVOR: artful
    SIMD: 1

  before_script:
    - ./ci/ubuntu_prep.sh
    - ./ci/bootstrap_boost.sh


# DISABLED for now
.Ubuntu Linux:ASAN:
  <<: *linux_cfg
  stage: build
  variables:
    ASAN: 1
    FLAVOR: zesty_asan

  before_script:
    - ./ci/ubuntu_prep.sh
    - ./ci/bootstrap_boost.sh



# DISABLED for now
.Ubuntu Linux:TSAN:
  <<: *linux_cfg
  stage: build
  variables:
    TSAN: 1
    FLAVOR: zesty_tsan

  before_script:
    - ./ci/ubuntu_prep.sh



# DISABLED: Shared runners avail for gitlab CI
#   don't include OS X
.OS X:
  stage: build
  variables:
    CC: clang
    CXX: clang++
  tags:
    - clang
    - osx

  script:
    - ./ci/build-gitlab.sh

# DISABLED for now
.Alpine Linux:
  stage: build
  image: alpine:latest
  variables:
    BUSYBOX_BASH: 1

  before_script:
    - apk add --update alpine-sdk autoconf automake libtool clang-dev cmake ninja qt5-qtbase-dev qt5-qttools-dev boost-dev ttf-freefont xvfb

  script:
    - ./ci/build-gitlab.sh

