version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
max_jobs: 2
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  matrix:
    - network: nano_live_network
      configuration: Release
    - network: nano_beta_network
      configuration: RelWithDebInfo
clone_folder: C:\projects\myproject
install:
- cmd: >-
    git submodule update --init --recursive

    cmake -DNANO_GUI=ON -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DACTIVE_NETWORK=%NETWORK% -DQt5_DIR="C:\Qt\5.9\msvc2017_64\lib\cmake\Qt5" -DNANO_SIMD_OPTIMIZATIONS=TRUE -DBoost_COMPILER="-vc141" -DBOOST_ROOT="C:/Libraries/boost_1_66_0" -DBOOST_LIBRARYDIR="C:/Libraries/boost_1_66_0/lib64-msvc-14.1" -G "Visual Studio 15 2017 Win64" -DIPHLPAPI_LIBRARY="C:/Program Files (x86)/Windows Kits/10/Lib/10.0.14393.0/um/x64/iphlpapi.lib" -DWINSOCK2_LIBRARY="C:/Program Files (x86)/Windows Kits/10/Lib/10.0.14393.0/um/x64/WS2_32.lib" .

- ps: Invoke-WebRequest -Uri https://aka.ms/vs/15/release/vc_redist.x64.exe -OutFile .\vc_redist.x64.exe
build:
  project: INSTALL.vcxproj
  parallel: true
  verbosity: minimal
after_build:
- ps: |
    if (Test-Path env:CSC_LINK) {
      $path = Join-Path -Path "$env:TMP" -ChildPath csc.p12
      [IO.File]::WriteAllBytes($path, [Convert]::FromBase64String($env:CSC_LINK))

      $args = -split 'sign /a /ph /tr http://timestamp.digicert.com /td sha256 /fd sha256'
      $args += @('/f', $path, '/p', $env:CSC_KEY_PASSWORD, "$env:APPVEYOR_BUILD_FOLDER\$env:CONFIGURATION\*.exe")
      . 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe' $args
    }
- cmd: >-
    cpack -C %CONFIGURATION% --verbose --config ./CPackConfig.cmake

    cpack -G ZIP -C %CONFIGURATION% --verbose --config ./CPackConfig.cmake
artifacts:
- path: nano*.zip
  name: nano_release_%network%
- path: Nano_Installer-*.exe
  name: Nano_Installer_%network%
