name: CI Testing
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "repo"
        default: "nanocurrency/nano-node"
        required: true
      ref:
        description: "tag to build"
        default: "develop"
        required: true
env:
  artifact: 1

jobs:
  linux_rpm_job:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - name: tag
        run: |
          echo "TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
          ref: ${{ github.event.inputs.ref }}
          repository: ${{ github.event.inputs.repo }}
      - name: CentOS base
        run: ci/build-docker-image.sh docker/ci/Dockerfile-centos thsfs/nano-env:centos
      - name: Debug the vars
        run: |
          echo "TAG: ${TAG}"
      - name: Build Artifact
        run: |
          docker run -e LIVE=1 -e PAT=${{ secrets.GITHUB_TOKEN }} -e TAG=$TAG -v ${GITHUB_WORKSPACE}:/workspace \
          -v artifacts:/root/rpmbuild/RPMS -v source:/root/rpmbuild/SOURCES \
          thsfs/nano-env:centos /bin/bash -c "ci/build-centos.sh"
          echo "Showing the files..."
          find ~/rpmbuild
          echo "Looking for the RPMs..."
          find ~/ -name '*.rpm'
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -rav ~/rpmbuild ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}

  test_deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - name: Create file
        run: |
          mkdir -p ~/rpmbuild/blah
          touch ~/rpmbuild/blah/blah.rpm
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -rav ~/rpmbuild ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}

